const $=s=>document.querySelector(s);let csrf='';
async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Errore');return d}
function money(c,curr='EUR'){return new Intl.NumberFormat('it-IT',{style:'currency',currency:curr}).format((Number(c)||0)/100)}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function checkSession(){try{const d=await api('/api/admin-session',{method:'GET',headers:{}});csrf=d.csrf;showApp();await loadOrders()}catch{}}
function showApp(){$('#admin-login').hidden=true;$('#admin-app').hidden=false}
$('#admin-login-btn').addEventListener('click',async()=>{const e=$('#login-error');e.classList.remove('show');try{const d=await api('/api/admin-login',{method:'POST',body:JSON.stringify({password:$('#admin-password').value})});csrf=d.csrf;showApp();await loadOrders()}catch(err){e.textContent='Credenziali non valide.';e.classList.add('show')}})
$('#refresh-orders').addEventListener('click',loadOrders);$('#filter-status').addEventListener('change',loadOrders);$('#filter-method').addEventListener('change',loadOrders);
async function loadOrders(){const p=new URLSearchParams();if($('#filter-status').value)p.set('status',$('#filter-status').value);if($('#filter-method').value)p.set('method',$('#filter-method').value);const d=await api('/api/admin-orders?'+p.toString(),{method:'GET',headers:{}});$('#admin-note').textContent=`${d.orders.length} ordini`;$('#orders-body').innerHTML=d.orders.map(row).join('')||'<tr><td colspan="8">Nessun ordine.</td></tr>';document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>action(b.dataset.id,b.dataset.action)))}
function row(o){const actions=[];if(['bank','paypal'].includes(o.paymentMethod)&&['IN_ATTESA_PAGAMENTO','PAGAMENTO_DA_VERIFICARE'].includes(o.orderStatus))actions.push(`<button class="admin-btn primary" data-id="${esc(o.id)}" data-action="confirm_manual">Conferma pagamento</button>`);if(['PAGATO','CONSEGNATO'].includes(o.orderStatus)){actions.push(`<button class="admin-btn" data-id="${esc(o.id)}" data-action="resend_delivery">Reinvia e-mail</button>`);actions.push(`<button class="admin-btn" data-id="${esc(o.id)}" data-action="regenerate_download">Rigenera link</button>`);}if(!['ANNULLATO','RIMBORSATO','CONSEGNATO'].includes(o.orderStatus))actions.push(`<button class="admin-btn danger" data-id="${esc(o.id)}" data-action="cancel">Annulla</button>`);if(['PAGATO','CONSEGNATO'].includes(o.orderStatus))actions.push(`<button class="admin-btn danger" data-id="${esc(o.id)}" data-action="mark_refunded">Segna rimborsato</button>`);return `<tr><td><strong>${esc(o.id)}</strong><br><small>${esc(o.paypalOrderId||'')}</small></td><td>${esc(o.customerName)}<br><small>${esc(o.email)}</small></td><td>${o.paymentMethod==='bank'?'Bonifico':'PayPal'}</td><td>${money(o.amountCents,o.currency)}</td><td>${esc(o.orderStatus)}</td><td>${esc(o.deliveryStatus)}<br><small>${o.downloadCount}/${o.maxDownloads} download${o.deliveryError?'<br>'+esc(o.deliveryError):''}</small></td><td>${new Date(o.createdAt).toLocaleString('it-IT')}</td><td><div class="admin-actions">${actions.join('')}</div></td></tr>`}
async function action(orderId,action){if(action==='confirm_manual'&&!confirm('Confermi di aver verificato personalmente che il pagamento è stato realmente ricevuto? Questa azione invierà Seller OS al cliente.'))return;if(action==='mark_refunded'&&!confirm('Hai già effettuato l’eventuale rimborso nel provider di pagamento? Questa azione aggiorna il registro e revoca il download.'))return;if(action==='cancel'&&!confirm('Annullare questo ordine?'))return;$('#admin-note').textContent='Elaborazione…';try{const d=await api('/api/admin-action',{method:'POST',headers:{'x-csrf-token':csrf},body:JSON.stringify({orderId,action})});if(d.downloadUrl){try{await navigator.clipboard.writeText(d.downloadUrl);$('#admin-note').textContent='Nuovo link generato e copiato negli appunti'}catch{$('#admin-note').textContent='Nuovo link generato: '+d.downloadUrl}}else{$('#admin-note').textContent=d.deliveryError?`Azione eseguita, ma invio email fallito: ${d.deliveryError}`:'Azione completata'}await loadOrders()}catch(e){$('#admin-note').textContent='Errore: '+e.message}}
checkSession();
