const $=s=>document.querySelector(s),params=new URLSearchParams(location.search),id=params.get('id'),token=params.get('token');let timer;
function money(c,curr='EUR'){return new Intl.NumberFormat('it-IT',{style:'currency',currency:curr}).format((Number(c)||0)/100)}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function fetchStatus(){if(!id||!token)throw new Error('Link ordine non valido');const r=await fetch(`/api/order-status?id=${encodeURIComponent(id)}&token=${encodeURIComponent(token)}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Ordine non trovato');return d}
function badge(s){const good=['PAGATO','CONSEGNATO'].includes(s),bad=['ANNULLATO','RIMBORSATO'].includes(s);return `<span class="co-pill ${good?'good':bad?'bad':'warn'}">${esc(s.replaceAll('_',' '))}</span>`}
function copyButtons(){document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='Copiato'}catch{b.textContent='Copia manualmente'}}))}
function render(o){
  const paid=['PAGATO','CONSEGNATO'].includes(o.orderStatus);
  $('#order-title').textContent=o.canDownload?'Seller OS è pronto':o.orderStatus==='CONSEGNATO'?'Seller OS è stato consegnato':o.orderStatus==='PAGATO'?'Pagamento verificato':o.orderStatus==='PAGAMENTO_DA_VERIFICARE'?'Pagamento da verificare':'Ordine ricevuto';
  let lead;
  if(o.canDownload) lead=`Il pagamento è stato verificato. Puoi scaricare Seller OS qui oppure utilizzare il link ricevuto a ${o.email}.`;
  else if(o.orderStatus==='CONSEGNATO') lead=`Abbiamo inviato Seller OS a ${o.email}. Se il link è scaduto contatta il supporto.`;
  else if(o.orderStatus==='PAGATO') lead='Pagamento verificato. Stiamo completando la consegna automatica di Seller OS.';
  else if(o.paymentMethod==='bank') lead='Riceverai Seller OS via e-mail e in questa pagina appena l’accredito bancario sarà verificato, normalmente entro 24 ore.';
  else lead='Riceverai Seller OS via e-mail e in questa pagina appena il pagamento PayPal sarà verificato, normalmente entro 24 ore.';
  $('#order-lead').textContent=lead;
  let details='';
  if(o.paymentMethod==='bank'&&o.bank&&!paid){details=`<div class="co-bank" style="margin-top:20px"><h3>Dati per il bonifico</h3><div class="co-bank-row"><span>Beneficiario</span><code>${esc(o.bank.accountName)}</code><button class="co-copy" data-copy="${esc(o.bank.accountName)}">Copia</button></div><div class="co-bank-row"><span>IBAN</span><code>${esc(o.bank.iban)}</code><button class="co-copy" data-copy="${esc(o.bank.iban)}">Copia</button></div><div class="co-bank-row"><span>Causale</span><code>${esc(o.bank.reference)}</code><button class="co-copy" data-copy="${esc(o.bank.reference)}">Copia</button></div></div>`}
  if(o.paymentMethod==='paypal'&&o.paypal&&['IN_ATTESA_PAGAMENTO','PAGAMENTO_DA_VERIFICARE'].includes(o.orderStatus)){details=`<div class="co-bank" style="margin-top:20px"><h3>Pagamento PayPal</h3><div class="co-bank-row"><span>Riferimento</span><code>${esc(o.paypal.reference)}</code><button class="co-copy" data-copy="${esc(o.paypal.reference)}">Copia</button></div><a class="co-primary" href="${esc(o.paypal.paymentUrl)}" target="_blank" rel="noopener noreferrer" style="margin-top:14px;text-decoration:none">Apri PayPal</a><p class="co-note" style="margin-top:12px">Se hai già pagato, non effettuare un secondo pagamento. Attendi la verifica.</p></div>`}
  let download='';
  if(o.canDownload){const remaining=Math.max(0,Number(o.maxDownloads||0)-Number(o.downloadCount||0));const expiry=o.downloadExpiresAt?new Date(o.downloadExpiresAt).toLocaleString('it-IT'):'';download=`<div class="co-bank" style="margin-top:20px"><span class="co-kicker">CONSEGNA DIGITALE</span><h3>Il tuo Customer Pack è disponibile</h3><p class="co-note">Scarica il pacchetto completo Seller OS 1.1. Il link resta protetto e collegato al tuo ordine.</p><a class="co-primary order-download" href="/api/order-download?id=${encodeURIComponent(o.id)}&token=${encodeURIComponent(token)}">Scarica Seller OS 1.1</a><div class="order-download-meta">${remaining} download disponibili${expiry?` · valido fino al ${esc(expiry)}`:''}</div></div>`}
  $('#order-box').innerHTML=`<div class="co-bank"><div class="co-bank-row"><span>Ordine</span><code>${esc(o.id)}</code><span></span></div><div class="co-bank-row"><span>Importo</span><code>${money(o.amountCents,o.currency)}</code><span></span></div><div class="co-bank-row"><span>Metodo</span><code>${o.paymentMethod==='bank'?'Bonifico bancario':'PayPal'}</code><span></span></div><div class="co-bank-row"><span>E-mail</span><code>${esc(o.email)}</code><span></span></div><div class="co-bank-row"><span>Stato</span><div>${badge(o.orderStatus)}</div><span></span></div></div>${download}${details}<p class="co-note">Questa pagina si aggiorna automaticamente. Conserva il link dell’ordine finché non hai completato il download.</p>`;
  copyButtons();if(['ANNULLATO','RIMBORSATO'].includes(o.orderStatus)){clearInterval(timer);timer=null}
}
async function refresh(){try{render(await fetchStatus())}catch(e){$('#order-error').textContent=e.message;$('#order-error').classList.add('show');clearInterval(timer)}}refresh();timer=setInterval(refresh,5000);
